# https://taskfile.dev

version: '3'


tasks:
  run:
    cmds:
      - go run ./cmd/app/main.go
  migrate:
    cmds:
      - go run ./cmd/migrator/main.go --migrations-path=./migrations/ --migrations-action={{.CLI_ARGS}}